name: Apply
on:
   pull_request:
     branches:
     - master
     - stg
     - main
     types: [closed]     

jobs:
  apply:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git-pr-release dev to stg
        if: contains(github.base_ref, 'master')
        run: |
          gh pr create -H "master" -B "stg" -t "元のPRと同じタイトル" --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

